

# GET http://localhost:5000/posts

# POST http://localhost:5000/home
# Content-Type: application/json

# {
#     "title": "Step Up",
#     "description": "Activity tracking web app that promotes sustainability",
#     "link": "link"
# }


# POST http://localhost:5000/
# Content-Type: application/json

# {
#     "name": "Step Up",
#     "email": "Activity tracking web app that promotes sustainability",
#     "description": "45345345345 r4e"
# }


#GET https://46qq1kyv3a.execute-api.eu-west-2.amazonaws.com/dev/post

# POST https://46qq1kyv3a.execute-api.eu-west-2.amazonaws.com/dev/post
# Content-Type: application/json

# {
#     "projectid": "1",
#     "title": "Step Up",
#     "content": "The activity tracking web application allows users to create accounts, link them to Strava for automatic activity logging, follow friends, and compete on leaderboards. As users complete activities, they can grow a virtual garden and engage with a sustainable community.",
#     "link" : "https://github.com/FeelingPeachy/StepUp"
# }


POST https://46qq1kyv3a.execute-api.eu-west-2.amazonaws.com/dev/contact
Content-Type: application/json

{
    "contactid": "1",
    "title": "Step Up",
    "content": "The activity tracking web application allows users to create accounts, link them to Strava for automatic activity logging, follow friends, and compete on leaderboards. As users complete activities, they can grow a virtual garden and engage with a sustainable community.",
    "link" : "https://github.com/FeelingPeachy/StepUp"
}



