

# GET http://localhost:5000/posts

# POST http://localhost:5000/home
# Content-Type: application/json

# {
#     "title": "Step Up",
#     "description": "Activity tracking web app that promotes sustainability",
#     "link": "link"
# }


# POST http://localhost:5000/
# Content-Type: application/json

# {
#     "name": "Step Up",
#     "email": "Activity tracking web app that promotes sustainability",
#     "description": "45345345345 r4e"
# }


#GET https://46qq1kyv3a.execute-api.eu-west-2.amazonaws.com/dev/post

POST https://46qq1kyv3a.execute-api.eu-west-2.amazonaws.com/dev/post
Content-Type: application/json

{
    "projectid": "2",
    "title": "Portfolio Code",
    "content": "link to repo containing code and assets used within this website",
    "Link" : "https://github.com/FeelingPeachy/personal-site"
}
